server:
  port: 9200

spring:
  application:
    name: ms-notification

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/sis-323}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:user}
    password: ${MAIL_PASSWORD:password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
