server:
  port: 9200

spring:
  application:
    name: ms-notification
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sis-323}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
